insert into CONNECTOR_CLIENT_MESSAGE
(
ID,
BACKEND_MESSAGE_ID,
ORIGINAL_SENDER,
FINAL_RECIPIENT,
FROM_PARTY_ID,
FROM_PARTY_TYPE,
FROM_PARTY_ROLE,
TO_PARTY_TYPE,
TO_PARTY_ROLE,
SERVICE,
ACTION,
STORAGE_STATUS,
STORAGE_INFO,
MESSAGE_STATUS,
CREATED
)
VALUES(
CLIENT_MESSAGE_SEQ.NEXTVAL,
'testMessage-${lab.id}-01',
'testSender',
'testRecipient',
'gw${lab.id}',
'urn:oasis:names:tc:ebcore:partyid-type:unregistered',
'GW',
'urn:oasis:names:tc:ebcore:partyid-type:unregistered',
'GW',
'Service1',
'Action1',
'STORED',
'${project.basedir}\labenv${lab.id}\domibus-connector-client-application\messages\testMessage',
'PREPARED',
CURRENT_TIMESTAMP
);