--liquibase formatted sql

--changeset StephanSpindler:initialBackendData_4
----------------------- Values for DOMIBUS_CONNECTOR_BACKEND_INFO ------------------------------

DELETE FROM DOMIBUS_CONNECTOR_BACKEND_INFO;

INSERT INTO DOMIBUS_CONNECTOR_BACKEND_INFO (ID, BACKEND_NAME, BACKEND_KEY_ALIAS, BACKEND_KEY_PASS, BACKEND_SERVICE_TYPE, BACKEND_DESCRIPTION, BACKEND_PUSH_ADDRESS, BACKEND_ENABLED, BACKEND_DEFAULT)
VALUES (1, 'cn=bob', 'bob', '', '', 'a bob backend - no push', null, true, true);

INSERT INTO DOMIBUS_CONNECTOR_BACKEND_INFO (ID, BACKEND_NAME, BACKEND_KEY_ALIAS, BACKEND_KEY_PASS, BACKEND_SERVICE_TYPE, BACKEND_DESCRIPTION, BACKEND_PUSH_ADDRESS, BACKEND_ENABLED, BACKEND_DEFAULT)
VALUES (2, 'cn=alice', 'alice', '', '', 'a alice backend with push', 'http://localhost:8042/services/domibusConnectorDeliveryWebservice', true, false);

DELETE FROM DOMIBUS_CONNECTOR_PARTY;


INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES
(1, 1, 'gw01', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:unregistered');

INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES
(2, 1, 'gw02', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:unregistered');

INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES
(3, 1, 'gw03', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:unregistered');

INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES
(4, 1, 'gw04', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:unregistered');

INSERT INTO DOMIBUS_CONNECTOR_PARTY (ID, FK_PMODE_SET, PARTY_ID, ROLE, PARTY_ID_TYPE) VALUES
(5, 1, 'gw05', 'GW', 'urn:oasis:names:tc:ebcore:partyid-type:unregistered');

DELETE FROM DOMIBUS_CONNECTOR_SERVICE;

INSERT INTO DOMIBUS_CONNECTOR_SERVICE (ID, FK_PMODE_SET, SERVICE, SERVICE_TYPE) VALUES (1, 1, 'Connector-TEST', 'urn:e-codex:services:');
INSERT INTO DOMIBUS_CONNECTOR_SERVICE (ID, FK_PMODE_SET, SERVICE, SERVICE_TYPE) VALUES (2, 1, 'System-TEST', 'urn:e-codex:services:');
INSERT INTO DOMIBUS_CONNECTOR_SERVICE (ID, FK_PMODE_SET, SERVICE, SERVICE_TYPE) VALUES (3, 1, 'Service1', 'urn:e-codex:services:');

DELETE FROM DOMIBUS_CONNECTOR_ACTION;

INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, "ACTION", PDF_REQUIRED)
VALUES (1, 1, 'SubmissionAcceptanceRejection', false);

INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, "ACTION", PDF_REQUIRED)
VALUES (2, 1, 'RelayREMMDAcceptanceRejection', false);

INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, "ACTION", PDF_REQUIRED)
VALUES (3, 1, 'DeliveryNonDeliveryToRecipient', false);

INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, "ACTION", PDF_REQUIRED)
VALUES (4, 1, 'RetrievalNonRetrievalToRecipient', false);

INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, "ACTION", PDF_REQUIRED)
VALUES (5, 1, 'System-TEST', false);

INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, "ACTION", PDF_REQUIRED)
VALUES (6, 1, 'Connector-TEST', false);

INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, "ACTION", PDF_REQUIRED)
VALUES (7, 1, 'Action1', false);

INSERT INTO DOMIBUS_CONNECTOR_ACTION (ID, FK_PMODE_SET, "ACTION", PDF_REQUIRED)
VALUES (8, 1, 'Action2', false);